// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_indices_sigma
arma::umat get_indices_sigma(const arma::uword& P);
RcppExport SEXP _dmrfit_get_indices_sigma(SEXP PSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::uword& >::type P(PSEXP);
    rcpp_result_gen = Rcpp::wrap(get_indices_sigma(P));
    return rcpp_result_gen;
END_RCPP
}
// get_which_stats
arma::uvec get_which_stats(const arma::uvec& n_categories, const arma::uword& n_thresholds);
RcppExport SEXP _dmrfit_get_which_stats(SEXP n_categoriesSEXP, SEXP n_thresholdsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::uvec& >::type n_categories(n_categoriesSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type n_thresholds(n_thresholdsSEXP);
    rcpp_result_gen = Rcpp::wrap(get_which_stats(n_categories, n_thresholds));
    return rcpp_result_gen;
END_RCPP
}
// get_category_stats
arma::vec get_category_stats(const arma::uvec& n_categories, const arma::uword& n_thresholds);
RcppExport SEXP _dmrfit_get_category_stats(SEXP n_categoriesSEXP, SEXP n_thresholdsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::uvec& >::type n_categories(n_categoriesSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type n_thresholds(n_thresholdsSEXP);
    rcpp_result_gen = Rcpp::wrap(get_category_stats(n_categories, n_thresholds));
    return rcpp_result_gen;
END_RCPP
}
// get_sufficient_stats_omrf
arma::vec get_sufficient_stats_omrf(const arma::mat& data, const arma::uvec& which_stats, const arma::vec& category_stats, const arma::umat& matrix_indices_sigma, const arma::uword& n_thresholds, const arma::uword& n_pars);
RcppExport SEXP _dmrfit_get_sufficient_stats_omrf(SEXP dataSEXP, SEXP which_statsSEXP, SEXP category_statsSEXP, SEXP matrix_indices_sigmaSEXP, SEXP n_thresholdsSEXP, SEXP n_parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type which_stats(which_statsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type category_stats(category_statsSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type matrix_indices_sigma(matrix_indices_sigmaSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type n_thresholds(n_thresholdsSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type n_pars(n_parsSEXP);
    rcpp_result_gen = Rcpp::wrap(get_sufficient_stats_omrf(data, which_stats, category_stats, matrix_indices_sigma, n_thresholds, n_pars));
    return rcpp_result_gen;
END_RCPP
}
// get_log_proposal_ratio
double get_log_proposal_ratio(const arma::vec& current_pars, const arma::vec& proposed_pars, const arma::vec& gradient_pseudo_current, const arma::vec& gradient_pseudo_proposed, const double& sigma2_R, const arma::mat& R_n);
RcppExport SEXP _dmrfit_get_log_proposal_ratio(SEXP current_parsSEXP, SEXP proposed_parsSEXP, SEXP gradient_pseudo_currentSEXP, SEXP gradient_pseudo_proposedSEXP, SEXP sigma2_RSEXP, SEXP R_nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type current_pars(current_parsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type proposed_pars(proposed_parsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gradient_pseudo_current(gradient_pseudo_currentSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gradient_pseudo_proposed(gradient_pseudo_proposedSEXP);
    Rcpp::traits::input_parameter< const double& >::type sigma2_R(sigma2_RSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type R_n(R_nSEXP);
    rcpp_result_gen = Rcpp::wrap(get_log_proposal_ratio(current_pars, proposed_pars, gradient_pseudo_current, gradient_pseudo_proposed, sigma2_R, R_n));
    return rcpp_result_gen;
END_RCPP
}
// get_log_prior_ratio
double get_log_prior_ratio(const arma::vec& theta_current, const arma::vec& theta_proposed, const arma::uword& n_thresholds, const arma::uword& n_pars, const double& thresholds_alpha, const double& thresholds_beta, const double& interactions_location, const double& interactions_scale);
RcppExport SEXP _dmrfit_get_log_prior_ratio(SEXP theta_currentSEXP, SEXP theta_proposedSEXP, SEXP n_thresholdsSEXP, SEXP n_parsSEXP, SEXP thresholds_alphaSEXP, SEXP thresholds_betaSEXP, SEXP interactions_locationSEXP, SEXP interactions_scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_current(theta_currentSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_proposed(theta_proposedSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type n_thresholds(n_thresholdsSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type n_pars(n_parsSEXP);
    Rcpp::traits::input_parameter< const double& >::type thresholds_alpha(thresholds_alphaSEXP);
    Rcpp::traits::input_parameter< const double& >::type thresholds_beta(thresholds_betaSEXP);
    Rcpp::traits::input_parameter< const double& >::type interactions_location(interactions_locationSEXP);
    Rcpp::traits::input_parameter< const double& >::type interactions_scale(interactions_scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(get_log_prior_ratio(theta_current, theta_proposed, n_thresholds, n_pars, thresholds_alpha, thresholds_beta, interactions_location, interactions_scale));
    return rcpp_result_gen;
END_RCPP
}
// omrf_pl_grad_logZ
arma::field<arma::vec> omrf_pl_grad_logZ(const arma::vec& pars, const arma::vec& current_pars, const arma::mat& data, const arma::vec& obs_stats, const arma::uword& P, const arma::umat& matrix_indices_sigma, const arma::uvec& which_stats, const arma::vec& category_stats, const arma::uvec& n_categories, const arma::uvec& lower_indices, const arma::uword& n_thresholds, const arma::uword& n_pars, const int& ncores, const bool& with_prior, const double& thresholds_alpha, const double& thresholds_beta, const double& interactions_location, const double& interactions_scale);
RcppExport SEXP _dmrfit_omrf_pl_grad_logZ(SEXP parsSEXP, SEXP current_parsSEXP, SEXP dataSEXP, SEXP obs_statsSEXP, SEXP PSEXP, SEXP matrix_indices_sigmaSEXP, SEXP which_statsSEXP, SEXP category_statsSEXP, SEXP n_categoriesSEXP, SEXP lower_indicesSEXP, SEXP n_thresholdsSEXP, SEXP n_parsSEXP, SEXP ncoresSEXP, SEXP with_priorSEXP, SEXP thresholds_alphaSEXP, SEXP thresholds_betaSEXP, SEXP interactions_locationSEXP, SEXP interactions_scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type current_pars(current_parsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type obs_stats(obs_statsSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type matrix_indices_sigma(matrix_indices_sigmaSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type which_stats(which_statsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type category_stats(category_statsSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type n_categories(n_categoriesSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type lower_indices(lower_indicesSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type n_thresholds(n_thresholdsSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type n_pars(n_parsSEXP);
    Rcpp::traits::input_parameter< const int& >::type ncores(ncoresSEXP);
    Rcpp::traits::input_parameter< const bool& >::type with_prior(with_priorSEXP);
    Rcpp::traits::input_parameter< const double& >::type thresholds_alpha(thresholds_alphaSEXP);
    Rcpp::traits::input_parameter< const double& >::type thresholds_beta(thresholds_betaSEXP);
    Rcpp::traits::input_parameter< const double& >::type interactions_location(interactions_locationSEXP);
    Rcpp::traits::input_parameter< const double& >::type interactions_scale(interactions_scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(omrf_pl_grad_logZ(pars, current_pars, data, obs_stats, P, matrix_indices_sigma, which_stats, category_stats, n_categories, lower_indices, n_thresholds, n_pars, ncores, with_prior, thresholds_alpha, thresholds_beta, interactions_location, interactions_scale));
    return rcpp_result_gen;
END_RCPP
}
// omrf_core_sampler
Rcpp::List omrf_core_sampler(const arma::mat& data, const arma::vec& pars, const arma::uvec& n_categories, const arma::uword& P, arma::uword& nsim, const arma::uword& burnin, const arma::vec& pmles, const arma::mat& current_scale, const arma::mat& new_scale, const arma::uword& adaptive_stage_n_iter, double sigma2, const double& thresholds_alpha, const double& thresholds_beta, const double& interactions_location, const double& interactions_scale);
RcppExport SEXP _dmrfit_omrf_core_sampler(SEXP dataSEXP, SEXP parsSEXP, SEXP n_categoriesSEXP, SEXP PSEXP, SEXP nsimSEXP, SEXP burninSEXP, SEXP pmlesSEXP, SEXP current_scaleSEXP, SEXP new_scaleSEXP, SEXP adaptive_stage_n_iterSEXP, SEXP sigma2SEXP, SEXP thresholds_alphaSEXP, SEXP thresholds_betaSEXP, SEXP interactions_locationSEXP, SEXP interactions_scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type n_categories(n_categoriesSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type P(PSEXP);
    Rcpp::traits::input_parameter< arma::uword& >::type nsim(nsimSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type pmles(pmlesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type current_scale(current_scaleSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type new_scale(new_scaleSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type adaptive_stage_n_iter(adaptive_stage_n_iterSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< const double& >::type thresholds_alpha(thresholds_alphaSEXP);
    Rcpp::traits::input_parameter< const double& >::type thresholds_beta(thresholds_betaSEXP);
    Rcpp::traits::input_parameter< const double& >::type interactions_location(interactions_locationSEXP);
    Rcpp::traits::input_parameter< const double& >::type interactions_scale(interactions_scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(omrf_core_sampler(data, pars, n_categories, P, nsim, burnin, pmles, current_scale, new_scale, adaptive_stage_n_iter, sigma2, thresholds_alpha, thresholds_beta, interactions_location, interactions_scale));
    return rcpp_result_gen;
END_RCPP
}
// optimize
Rcpp::List optimize(const arma::mat& data, const arma::vec& parinit, const arma::uvec& n_categories, const arma::uword& P, const double& f_term, const double& m_term, const arma::uword& n_iter_max, const double& rinit, const double& rmax, const bool& with_prior, const double& epsilon, const int& ncores, const double& thresholds_alpha, const double& thresholds_beta, const double& interactions_location, const double& interactions_scale);
RcppExport SEXP _dmrfit_optimize(SEXP dataSEXP, SEXP parinitSEXP, SEXP n_categoriesSEXP, SEXP PSEXP, SEXP f_termSEXP, SEXP m_termSEXP, SEXP n_iter_maxSEXP, SEXP rinitSEXP, SEXP rmaxSEXP, SEXP with_priorSEXP, SEXP epsilonSEXP, SEXP ncoresSEXP, SEXP thresholds_alphaSEXP, SEXP thresholds_betaSEXP, SEXP interactions_locationSEXP, SEXP interactions_scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type parinit(parinitSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type n_categories(n_categoriesSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const double& >::type f_term(f_termSEXP);
    Rcpp::traits::input_parameter< const double& >::type m_term(m_termSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type n_iter_max(n_iter_maxSEXP);
    Rcpp::traits::input_parameter< const double& >::type rinit(rinitSEXP);
    Rcpp::traits::input_parameter< const double& >::type rmax(rmaxSEXP);
    Rcpp::traits::input_parameter< const bool& >::type with_prior(with_priorSEXP);
    Rcpp::traits::input_parameter< const double& >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< const int& >::type ncores(ncoresSEXP);
    Rcpp::traits::input_parameter< const double& >::type thresholds_alpha(thresholds_alphaSEXP);
    Rcpp::traits::input_parameter< const double& >::type thresholds_beta(thresholds_betaSEXP);
    Rcpp::traits::input_parameter< const double& >::type interactions_location(interactions_locationSEXP);
    Rcpp::traits::input_parameter< const double& >::type interactions_scale(interactions_scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(optimize(data, parinit, n_categories, P, f_term, m_term, n_iter_max, rinit, rmax, with_prior, epsilon, ncores, thresholds_alpha, thresholds_beta, interactions_location, interactions_scale));
    return rcpp_result_gen;
END_RCPP
}
// optimize_with_structure
Rcpp::List optimize_with_structure(const arma::mat& data, const arma::vec& parinit, const arma::vec& structure, const arma::uvec& n_categories, const arma::uword& P, const double& f_term, const double& m_term, const arma::uword& n_iter_max, const double& rinit, const double& rmax, const bool& with_prior, const double& epsilon, const int& ncores, const double& thresholds_alpha, const double& thresholds_beta, const double& interactions_location, const double& interactions_scale);
RcppExport SEXP _dmrfit_optimize_with_structure(SEXP dataSEXP, SEXP parinitSEXP, SEXP structureSEXP, SEXP n_categoriesSEXP, SEXP PSEXP, SEXP f_termSEXP, SEXP m_termSEXP, SEXP n_iter_maxSEXP, SEXP rinitSEXP, SEXP rmaxSEXP, SEXP with_priorSEXP, SEXP epsilonSEXP, SEXP ncoresSEXP, SEXP thresholds_alphaSEXP, SEXP thresholds_betaSEXP, SEXP interactions_locationSEXP, SEXP interactions_scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type parinit(parinitSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type structure(structureSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type n_categories(n_categoriesSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const double& >::type f_term(f_termSEXP);
    Rcpp::traits::input_parameter< const double& >::type m_term(m_termSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type n_iter_max(n_iter_maxSEXP);
    Rcpp::traits::input_parameter< const double& >::type rinit(rinitSEXP);
    Rcpp::traits::input_parameter< const double& >::type rmax(rmaxSEXP);
    Rcpp::traits::input_parameter< const bool& >::type with_prior(with_priorSEXP);
    Rcpp::traits::input_parameter< const double& >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< const int& >::type ncores(ncoresSEXP);
    Rcpp::traits::input_parameter< const double& >::type thresholds_alpha(thresholds_alphaSEXP);
    Rcpp::traits::input_parameter< const double& >::type thresholds_beta(thresholds_betaSEXP);
    Rcpp::traits::input_parameter< const double& >::type interactions_location(interactions_locationSEXP);
    Rcpp::traits::input_parameter< const double& >::type interactions_scale(interactions_scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(optimize_with_structure(data, parinit, structure, n_categories, P, f_term, m_term, n_iter_max, rinit, rmax, with_prior, epsilon, ncores, thresholds_alpha, thresholds_beta, interactions_location, interactions_scale));
    return rcpp_result_gen;
END_RCPP
}
// optimize_profile
Rcpp::List optimize_profile(const arma::mat& data, const arma::vec& parinit, const arma::uvec& which_parconstr, const arma::vec& parconstr, const arma::uvec& n_categories, const arma::uword& P, const double& f_term, const double& m_term, const arma::uword& n_iter_max, const double& rinit, const double& rmax, const bool& with_prior, const double& epsilon, const int& ncores, const double& thresholds_alpha, const double& thresholds_beta, const double& interactions_location, const double& interactions_scale);
RcppExport SEXP _dmrfit_optimize_profile(SEXP dataSEXP, SEXP parinitSEXP, SEXP which_parconstrSEXP, SEXP parconstrSEXP, SEXP n_categoriesSEXP, SEXP PSEXP, SEXP f_termSEXP, SEXP m_termSEXP, SEXP n_iter_maxSEXP, SEXP rinitSEXP, SEXP rmaxSEXP, SEXP with_priorSEXP, SEXP epsilonSEXP, SEXP ncoresSEXP, SEXP thresholds_alphaSEXP, SEXP thresholds_betaSEXP, SEXP interactions_locationSEXP, SEXP interactions_scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type parinit(parinitSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type which_parconstr(which_parconstrSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type parconstr(parconstrSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type n_categories(n_categoriesSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const double& >::type f_term(f_termSEXP);
    Rcpp::traits::input_parameter< const double& >::type m_term(m_termSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type n_iter_max(n_iter_maxSEXP);
    Rcpp::traits::input_parameter< const double& >::type rinit(rinitSEXP);
    Rcpp::traits::input_parameter< const double& >::type rmax(rmaxSEXP);
    Rcpp::traits::input_parameter< const bool& >::type with_prior(with_priorSEXP);
    Rcpp::traits::input_parameter< const double& >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< const int& >::type ncores(ncoresSEXP);
    Rcpp::traits::input_parameter< const double& >::type thresholds_alpha(thresholds_alphaSEXP);
    Rcpp::traits::input_parameter< const double& >::type thresholds_beta(thresholds_betaSEXP);
    Rcpp::traits::input_parameter< const double& >::type interactions_location(interactions_locationSEXP);
    Rcpp::traits::input_parameter< const double& >::type interactions_scale(interactions_scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(optimize_profile(data, parinit, which_parconstr, parconstr, n_categories, P, f_term, m_term, n_iter_max, rinit, rmax, with_prior, epsilon, ncores, thresholds_alpha, thresholds_beta, interactions_location, interactions_scale));
    return rcpp_result_gen;
END_RCPP
}
// mvnrnd_arma
arma::mat mvnrnd_arma(const arma::vec& mu, const arma::mat& Sigma, int n);
RcppExport SEXP _dmrfit_mvnrnd_arma(SEXP muSEXP, SEXP SigmaSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(mvnrnd_arma(mu, Sigma, n));
    return rcpp_result_gen;
END_RCPP
}
// npseudologlik
double npseudologlik(const arma::vec& pars, const arma::mat& data, const arma::uword& P, const arma::uvec& n_categories, const bool& with_prior, const int& ncores, const double& thresholds_alpha, const double& thresholds_beta, const double& interactions_location, const double& interactions_scale);
RcppExport SEXP _dmrfit_npseudologlik(SEXP parsSEXP, SEXP dataSEXP, SEXP PSEXP, SEXP n_categoriesSEXP, SEXP with_priorSEXP, SEXP ncoresSEXP, SEXP thresholds_alphaSEXP, SEXP thresholds_betaSEXP, SEXP interactions_locationSEXP, SEXP interactions_scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type n_categories(n_categoriesSEXP);
    Rcpp::traits::input_parameter< const bool& >::type with_prior(with_priorSEXP);
    Rcpp::traits::input_parameter< const int& >::type ncores(ncoresSEXP);
    Rcpp::traits::input_parameter< const double& >::type thresholds_alpha(thresholds_alphaSEXP);
    Rcpp::traits::input_parameter< const double& >::type thresholds_beta(thresholds_betaSEXP);
    Rcpp::traits::input_parameter< const double& >::type interactions_location(interactions_locationSEXP);
    Rcpp::traits::input_parameter< const double& >::type interactions_scale(interactions_scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(npseudologlik(pars, data, P, n_categories, with_prior, ncores, thresholds_alpha, thresholds_beta, interactions_location, interactions_scale));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dmrfit_get_indices_sigma", (DL_FUNC) &_dmrfit_get_indices_sigma, 1},
    {"_dmrfit_get_which_stats", (DL_FUNC) &_dmrfit_get_which_stats, 2},
    {"_dmrfit_get_category_stats", (DL_FUNC) &_dmrfit_get_category_stats, 2},
    {"_dmrfit_get_sufficient_stats_omrf", (DL_FUNC) &_dmrfit_get_sufficient_stats_omrf, 6},
    {"_dmrfit_get_log_proposal_ratio", (DL_FUNC) &_dmrfit_get_log_proposal_ratio, 6},
    {"_dmrfit_get_log_prior_ratio", (DL_FUNC) &_dmrfit_get_log_prior_ratio, 8},
    {"_dmrfit_omrf_pl_grad_logZ", (DL_FUNC) &_dmrfit_omrf_pl_grad_logZ, 18},
    {"_dmrfit_omrf_core_sampler", (DL_FUNC) &_dmrfit_omrf_core_sampler, 15},
    {"_dmrfit_optimize", (DL_FUNC) &_dmrfit_optimize, 16},
    {"_dmrfit_optimize_with_structure", (DL_FUNC) &_dmrfit_optimize_with_structure, 17},
    {"_dmrfit_optimize_profile", (DL_FUNC) &_dmrfit_optimize_profile, 18},
    {"_dmrfit_mvnrnd_arma", (DL_FUNC) &_dmrfit_mvnrnd_arma, 3},
    {"_dmrfit_npseudologlik", (DL_FUNC) &_dmrfit_npseudologlik, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_dmrfit(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
