// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// optimize
Rcpp::List optimize(arma::mat data, arma::vec parinit, arma::uvec n_categories, arma::uword P, double f_term, double m_term, arma::uword n_iter_max, double rinit, double rmax, bool with_prior, double epsilon, int ncores);
RcppExport SEXP _dmrfit_optimize(SEXP dataSEXP, SEXP parinitSEXP, SEXP n_categoriesSEXP, SEXP PSEXP, SEXP f_termSEXP, SEXP m_termSEXP, SEXP n_iter_maxSEXP, SEXP rinitSEXP, SEXP rmaxSEXP, SEXP with_priorSEXP, SEXP epsilonSEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type parinit(parinitSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type n_categories(n_categoriesSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type P(PSEXP);
    Rcpp::traits::input_parameter< double >::type f_term(f_termSEXP);
    Rcpp::traits::input_parameter< double >::type m_term(m_termSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n_iter_max(n_iter_maxSEXP);
    Rcpp::traits::input_parameter< double >::type rinit(rinitSEXP);
    Rcpp::traits::input_parameter< double >::type rmax(rmaxSEXP);
    Rcpp::traits::input_parameter< bool >::type with_prior(with_priorSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(optimize(data, parinit, n_categories, P, f_term, m_term, n_iter_max, rinit, rmax, with_prior, epsilon, ncores));
    return rcpp_result_gen;
END_RCPP
}
// optimize_with_structure
Rcpp::List optimize_with_structure(arma::mat data, arma::vec parinit, arma::vec structure, arma::uvec n_categories, arma::uword P, double f_term, double m_term, arma::uword n_iter_max, double rinit, double rmax, bool with_prior, double epsilon, int ncores);
RcppExport SEXP _dmrfit_optimize_with_structure(SEXP dataSEXP, SEXP parinitSEXP, SEXP structureSEXP, SEXP n_categoriesSEXP, SEXP PSEXP, SEXP f_termSEXP, SEXP m_termSEXP, SEXP n_iter_maxSEXP, SEXP rinitSEXP, SEXP rmaxSEXP, SEXP with_priorSEXP, SEXP epsilonSEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type parinit(parinitSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type structure(structureSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type n_categories(n_categoriesSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type P(PSEXP);
    Rcpp::traits::input_parameter< double >::type f_term(f_termSEXP);
    Rcpp::traits::input_parameter< double >::type m_term(m_termSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n_iter_max(n_iter_maxSEXP);
    Rcpp::traits::input_parameter< double >::type rinit(rinitSEXP);
    Rcpp::traits::input_parameter< double >::type rmax(rmaxSEXP);
    Rcpp::traits::input_parameter< bool >::type with_prior(with_priorSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(optimize_with_structure(data, parinit, structure, n_categories, P, f_term, m_term, n_iter_max, rinit, rmax, with_prior, epsilon, ncores));
    return rcpp_result_gen;
END_RCPP
}
// optimize_profile
Rcpp::List optimize_profile(arma::mat data, arma::vec parinit, arma::uvec which_parconstr, arma::vec parconstr, arma::uvec n_categories, arma::uword P, double f_term, double m_term, arma::uword n_iter_max, double rinit, double rmax, bool with_prior, double epsilon, int ncores);
RcppExport SEXP _dmrfit_optimize_profile(SEXP dataSEXP, SEXP parinitSEXP, SEXP which_parconstrSEXP, SEXP parconstrSEXP, SEXP n_categoriesSEXP, SEXP PSEXP, SEXP f_termSEXP, SEXP m_termSEXP, SEXP n_iter_maxSEXP, SEXP rinitSEXP, SEXP rmaxSEXP, SEXP with_priorSEXP, SEXP epsilonSEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type parinit(parinitSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type which_parconstr(which_parconstrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type parconstr(parconstrSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type n_categories(n_categoriesSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type P(PSEXP);
    Rcpp::traits::input_parameter< double >::type f_term(f_termSEXP);
    Rcpp::traits::input_parameter< double >::type m_term(m_termSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n_iter_max(n_iter_maxSEXP);
    Rcpp::traits::input_parameter< double >::type rinit(rinitSEXP);
    Rcpp::traits::input_parameter< double >::type rmax(rmaxSEXP);
    Rcpp::traits::input_parameter< bool >::type with_prior(with_priorSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(optimize_profile(data, parinit, which_parconstr, parconstr, n_categories, P, f_term, m_term, n_iter_max, rinit, rmax, with_prior, epsilon, ncores));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dmrfit_optimize", (DL_FUNC) &_dmrfit_optimize, 12},
    {"_dmrfit_optimize_with_structure", (DL_FUNC) &_dmrfit_optimize_with_structure, 13},
    {"_dmrfit_optimize_profile", (DL_FUNC) &_dmrfit_optimize_profile, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_dmrfit(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
