# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_omrf_core_sampler <- function(data, pars, n_categories, P, nsim, burnin, pmles, current_scale, new_scale, adaptive_stage_n_iter = 500L, sigma2 = 1.0, thresholds_alpha = 0.5, thresholds_beta = 0.5, interactions_location = 0.0, interactions_scale = 2.5) {
    .Call(`_dmrfit_cpp_omrf_core_sampler`, data, pars, n_categories, P, nsim, burnin, pmles, current_scale, new_scale, adaptive_stage_n_iter, sigma2, thresholds_alpha, thresholds_beta, interactions_location, interactions_scale)
}

cpp_optimize <- function(data, parinit, n_categories, P, f_term, m_term, n_iter_max = 100L, rinit = 1.0, rmax = 10.0, with_prior = FALSE, epsilon = 1e-06, ncores = 1L, thresholds_alpha = 0.5, thresholds_beta = 0.5, interactions_location = 0.0, interactions_scale = 2.5) {
    .Call(`_dmrfit_cpp_optimize`, data, parinit, n_categories, P, f_term, m_term, n_iter_max, rinit, rmax, with_prior, epsilon, ncores, thresholds_alpha, thresholds_beta, interactions_location, interactions_scale)
}

cpp_optimize_with_structure <- function(data, parinit, structure, n_categories, P, f_term, m_term, n_iter_max = 100L, rinit = 1.0, rmax = 10.0, with_prior = FALSE, epsilon = 1e-06, ncores = 1L, thresholds_alpha = 0.5, thresholds_beta = 0.5, interactions_location = 0.0, interactions_scale = 2.5) {
    .Call(`_dmrfit_cpp_optimize_with_structure`, data, parinit, structure, n_categories, P, f_term, m_term, n_iter_max, rinit, rmax, with_prior, epsilon, ncores, thresholds_alpha, thresholds_beta, interactions_location, interactions_scale)
}

cpp_optimize_profile <- function(data, parinit, which_parconstr, parconstr, n_categories, P, f_term, m_term, n_iter_max = 100L, rinit = 1.0, rmax = 10.0, with_prior = FALSE, epsilon = 1e-06, ncores = 1L, thresholds_alpha = 0.5, thresholds_beta = 0.5, interactions_location = 0.0, interactions_scale = 2.5) {
    .Call(`_dmrfit_cpp_optimize_profile`, data, parinit, which_parconstr, parconstr, n_categories, P, f_term, m_term, n_iter_max, rinit, rmax, with_prior, epsilon, ncores, thresholds_alpha, thresholds_beta, interactions_location, interactions_scale)
}

cpp_mvnrnd_arma <- function(mu, Sigma, n) {
    .Call(`_dmrfit_cpp_mvnrnd_arma`, mu, Sigma, n)
}

dmrf_deriv <- function(pars, data, P, n_categories, with_prior, ncores, thresholds_alpha, thresholds_beta, interactions_location, interactions_scale) {
    .Call(`_dmrfit_dmrf_deriv`, pars, data, P, n_categories, with_prior, ncores, thresholds_alpha, thresholds_beta, interactions_location, interactions_scale)
}

cpp_npseudologlik <- function(pars, data, P, n_categories, with_prior, ncores, thresholds_alpha, thresholds_beta, interactions_location, interactions_scale) {
    .Call(`_dmrfit_cpp_npseudologlik`, pars, data, P, n_categories, with_prior, ncores, thresholds_alpha, thresholds_beta, interactions_location, interactions_scale)
}

