# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_indices_sigma <- function(P) {
    .Call(`_dmrfit_get_indices_sigma`, P)
}

get_which_stats <- function(n_categories, n_thresholds) {
    .Call(`_dmrfit_get_which_stats`, n_categories, n_thresholds)
}

get_category_stats <- function(n_categories, n_thresholds) {
    .Call(`_dmrfit_get_category_stats`, n_categories, n_thresholds)
}

get_sufficient_stats_omrf <- function(data, which_stats, category_stats, matrix_indices_sigma, n_thresholds, n_pars) {
    .Call(`_dmrfit_get_sufficient_stats_omrf`, data, which_stats, category_stats, matrix_indices_sigma, n_thresholds, n_pars)
}

get_log_proposal_ratio <- function(current_pars, proposed_pars, gradient_pseudo_current, gradient_pseudo_proposed, sigma2_R, R_n) {
    .Call(`_dmrfit_get_log_proposal_ratio`, current_pars, proposed_pars, gradient_pseudo_current, gradient_pseudo_proposed, sigma2_R, R_n)
}

get_log_prior_ratio <- function(theta_current, theta_proposed, n_thresholds, n_pars, thresholds_alpha, thresholds_beta, interactions_location, interactions_scale) {
    .Call(`_dmrfit_get_log_prior_ratio`, theta_current, theta_proposed, n_thresholds, n_pars, thresholds_alpha, thresholds_beta, interactions_location, interactions_scale)
}

omrf_pl_grad_logZ <- function(pars, current_pars, data, obs_stats, P, matrix_indices_sigma, which_stats, category_stats, n_categories, lower_indices, n_thresholds, n_pars, ncores, with_prior, thresholds_alpha, thresholds_beta, interactions_location, interactions_scale) {
    .Call(`_dmrfit_omrf_pl_grad_logZ`, pars, current_pars, data, obs_stats, P, matrix_indices_sigma, which_stats, category_stats, n_categories, lower_indices, n_thresholds, n_pars, ncores, with_prior, thresholds_alpha, thresholds_beta, interactions_location, interactions_scale)
}

omrf_core_sampler <- function(data, pars, n_categories, P, nsim, burnin, pmles, current_scale, new_scale, adaptive_stage_n_iter = 500L, sigma2 = 1.0, thresholds_alpha = 0.5, thresholds_beta = 0.5, interactions_location = 0.0, interactions_scale = 2.5) {
    .Call(`_dmrfit_omrf_core_sampler`, data, pars, n_categories, P, nsim, burnin, pmles, current_scale, new_scale, adaptive_stage_n_iter, sigma2, thresholds_alpha, thresholds_beta, interactions_location, interactions_scale)
}

optimize <- function(data, parinit, n_categories, P, f_term, m_term, n_iter_max = 100L, rinit = 1.0, rmax = 10.0, with_prior = FALSE, epsilon = 1e-06, ncores = 1L, thresholds_alpha = 0.5, thresholds_beta = 0.5, interactions_location = 0.0, interactions_scale = 2.5) {
    .Call(`_dmrfit_optimize`, data, parinit, n_categories, P, f_term, m_term, n_iter_max, rinit, rmax, with_prior, epsilon, ncores, thresholds_alpha, thresholds_beta, interactions_location, interactions_scale)
}

optimize_with_structure <- function(data, parinit, structure, n_categories, P, f_term, m_term, n_iter_max = 100L, rinit = 1.0, rmax = 10.0, with_prior = FALSE, epsilon = 1e-06, ncores = 1L, thresholds_alpha = 0.5, thresholds_beta = 0.5, interactions_location = 0.0, interactions_scale = 2.5) {
    .Call(`_dmrfit_optimize_with_structure`, data, parinit, structure, n_categories, P, f_term, m_term, n_iter_max, rinit, rmax, with_prior, epsilon, ncores, thresholds_alpha, thresholds_beta, interactions_location, interactions_scale)
}

optimize_profile <- function(data, parinit, which_parconstr, parconstr, n_categories, P, f_term, m_term, n_iter_max = 100L, rinit = 1.0, rmax = 10.0, with_prior = FALSE, epsilon = 1e-06, ncores = 1L, thresholds_alpha = 0.5, thresholds_beta = 0.5, interactions_location = 0.0, interactions_scale = 2.5) {
    .Call(`_dmrfit_optimize_profile`, data, parinit, which_parconstr, parconstr, n_categories, P, f_term, m_term, n_iter_max, rinit, rmax, with_prior, epsilon, ncores, thresholds_alpha, thresholds_beta, interactions_location, interactions_scale)
}

mvnrnd_arma <- function(mu, Sigma, n) {
    .Call(`_dmrfit_mvnrnd_arma`, mu, Sigma, n)
}

npseudologlik <- function(pars, data, P, n_categories, with_prior, ncores, thresholds_alpha, thresholds_beta, interactions_location, interactions_scale) {
    .Call(`_dmrfit_npseudologlik`, pars, data, P, n_categories, with_prior, ncores, thresholds_alpha, thresholds_beta, interactions_location, interactions_scale)
}

