# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

optimize <- function(data, parinit, n_categories, P, f_term, m_term, n_iter_max = 100L, rinit = 1.0, rmax = 10.0, with_prior = FALSE, epsilon = 1e-06, ncores = 1L) {
    .Call(`_dmrfit_optimize`, data, parinit, n_categories, P, f_term, m_term, n_iter_max, rinit, rmax, with_prior, epsilon, ncores)
}

optimize_with_structure <- function(data, parinit, structure, n_categories, P, f_term, m_term, n_iter_max = 100L, rinit = 1.0, rmax = 10.0, with_prior = FALSE, epsilon = 1e-06, ncores = 1L) {
    .Call(`_dmrfit_optimize_with_structure`, data, parinit, structure, n_categories, P, f_term, m_term, n_iter_max, rinit, rmax, with_prior, epsilon, ncores)
}

optimize_profile <- function(data, parinit, which_parconstr, parconstr, n_categories, P, f_term, m_term, n_iter_max = 100L, rinit = 1.0, rmax = 10.0, with_prior = FALSE, epsilon = 1e-06, ncores = 1L) {
    .Call(`_dmrfit_optimize_profile`, data, parinit, which_parconstr, parconstr, n_categories, P, f_term, m_term, n_iter_max, rinit, rmax, with_prior, epsilon, ncores)
}

